name: validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    uses: trussworks/shared-actions/.github/workflows/validate-python.yml@main

  additional-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Run nosetests
        run: nosetests

      - name: Test build
        run: make archive
